name: Build e Deploy Java no K3s

on:
  push:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

#      - name: Autenticação no Docker Hub
#        uses: docker/login-action@v2.1.0
#        with:
#          username: ${{secrets.DOCKERHUB_USER}}
#          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Construção da imagem Docker
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./src
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/events:${{github.run_number}}
            ${{ secrets.DOCKERHUB_USERNAME }}/events:latest

#      - name: Build da imagem Docker
#        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/java-app:latest .

#      - name: Push da imagem Docker
#        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/java-app:latest

      - name: Deploy no Kubernetes
        run: kubectl apply -f k8s/deployment.yaml

  CD:
    runs-on: self-hosted

    needs: [CI]
    steps:
      - uses: actions/checkout@v3

      - name: Definindo o context
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}